trigger:
- master

variables:
  DisplayVersion: $[counter(variables['DisplayPrefix'], 1)]

stages:
- stage: build
  displayName: 'build'
  jobs:
  - job: build
    displayName: 'windows-msvc'
    pool:
      vmImage: windows-2019
    steps:
    - template: ./.ci/templates/sync-source.yml
      parameters:
        artifactSource: $(parameters.artifactSource)
        needSubmodules: 'true'
    - template: ./.ci/templates/build-msvc.yml
      parameters:
        artifactSource: 'false'
        cache: $(parameters.cache)
        version: $(DisplayVersion)